import { draftMode } from 'next/headers';
import { notFound } from 'next/navigation';

import { REGIONS } from '@/lib/constants';
import { getContentfulClient } from '@/lib/contentful/get-client';
import type { ContentfulPageResponse } from '@/lib/contentful/types';
import { cn } from '@/lib/utils';

import { Blocks } from '@/components/blocks';
import { PlanSelection } from '@/components/plan-selection';
import { PricingTable } from '@/components/pricing-table';
import { Sources } from '@/components/sources';
import { DotPattern } from '@/components/ui/dot-pattern';

// false: Disallow rendering dynamic params that are not generated by generateStaticParams.
export const dynamicParams = false;

export function generateStaticParams() {
  return REGIONS.map((page) => ({
    region: page,
  }));
}

export async function generateMetadata({ params }: Readonly<{ params: { region: (typeof REGIONS)[number] } }>) {
  const { isEnabled } = draftMode();
  const cf = getContentfulClient(isEnabled);
  const entry = (await cf.getEntries({
    content_type: 'page',
    'fields.slug': params.region,
    limit: 1,
    include: 10,
    locale: params.region,
  })) as unknown as ContentfulPageResponse;

  if (!entry.items.length) {
    notFound();
  }

  const content = entry.items[0].fields;

  return {
    title: content.title,
    description: content.description,
    openGraph: {
      images: [
        {
          url: `/api/og?title=${content.title}`,
          width: 1200,
          height: 630,
          alt: content.description,
        },
      ],
    },
  };
}

export default async function Page({ params }: Readonly<{ params: { region: (typeof REGIONS)[number] } }>) {
  const { isEnabled } = draftMode();
  const cf = getContentfulClient(isEnabled);
  const entry = (await cf.getEntries({
    content_type: 'page',
    'fields.slug': params.region,
    limit: 1,
    include: 10,
    locale: params.region,
  })) as unknown as ContentfulPageResponse;

  if (!entry.items.length) {
    notFound();
  }

  const content = entry.items[0].fields;

  return (
    <main className="mt-16 space-y-16 md:mt-40 md:space-y-40">
      <DotPattern
        width={20}
        height={20}
        cx={1}
        cy={1}
        cr={1}
        className={cn('z-0 [mask-image:linear-gradient(to_bottom,white,transparent,transparent)]')}
      />

      <Blocks region={params.region} blocks={content.blocks} />

      <Sources />
      <PlanSelection />
      <PricingTable />
    </main>
  );
}
