import { draftMode } from 'next/headers';
import { notFound } from 'next/navigation';

import { REGIONS } from '@/lib/constants';
import { getContentfulClient } from '@/lib/contentful/get-client';
import type { ContentfulPageResponse } from '@/lib/contentful/types';

import { AccountantForm } from '@/components/accountant-form';
import { Blocks } from '@/components/blocks';
import { GetStartedButton } from '@/components/get-started-button';
import { PlanSelection } from '@/components/plan-selection';
import { PricingTable } from '@/components/pricing-table';
import { Sources } from '@/components/sources';

// false: Disallow rendering dynamic params that are not generated by generateStaticParams.
export const dynamicParams = false;

export function generateStaticParams() {
  return REGIONS.map((page) => ({
    region: page,
  }));
}

export async function generateMetadata({ params }: Readonly<{ params: { region: (typeof REGIONS)[number] } }>) {
  const cf = getContentfulClient();
  const entry = (await cf.getEntries({
    content_type: 'page',
    'fields.slug': params.region,
    limit: 1,
    include: 10,
    locale: params.region,
  })) as unknown as ContentfulPageResponse;

  if (!entry.items.length) {
    notFound();
  }

  const content = entry.items[0].fields;

  return {
    title: content.title,
    description: content.description,
    openGraph: {
      images: [
        {
          url: `/api/og?title=${content.title}`,
          width: 1200,
          height: 630,
          alt: content.description,
        },
      ],
    },
  };
}

export default async function Page({ params }: Readonly<{ params: { region: (typeof REGIONS)[number] } }>) {
  const { isEnabled } = draftMode();
  const cf = getContentfulClient(isEnabled);
  const entry = (await cf.getEntries({
    content_type: 'page',
    'fields.slug': params.region,
    limit: 1,
    include: 10,
    locale: params.region,
  })) as unknown as ContentfulPageResponse;

  if (!entry.items.length) {
    notFound();
  }

  const content = entry.items[0].fields;

  return (
    <main className="mt-16 space-y-16 md:mt-40 md:space-y-40">
      <Blocks region={params.region} blocks={content.blocks} />

      <Sources />
      <PlanSelection />
      <PricingTable />

      <div className="container py-40">
        <h2 className="mb-2 text-balance text-center text-2xl md:text-3xl">Säkrare och enklare affärer.</h2>
        <p className="mx-auto mb-10 max-w-prose text-balance text-center text-xl text-tic-lighter md:text-2xl">
          Vår AI-plattformen övervakar ständigt hundratals datakällor för att identifiera avvikelser och mönster i register,
          årsredovisningar och andra källor. Få koll på vem du gör affärer och slipp obehagliga överraskningar.
        </p>
        <div className="mx-auto flex justify-center gap-3">
          <GetStartedButton plan="Free" />
          <GetStartedButton plan="Premium" />
        </div>
      </div>

      <AccountantForm />
    </main>
  );
}
